

GET http://localhost:5000/questions/

###

POST http://localhost:5000/questions/
Content-Type: application/json

{
"author" : "Mohammad",
"title"  : "cats",
"content": "-------------",
"category": "animals",
"type": "external"

}


### 

DELETE  http://localhost:5000/questions/98897867866

###

PUT http://localhost:5000/questions/73ece9d3385bcaee5060a487
Content-Type: application/json

{

"author" : "Sara",
"title"  : "tigers",
"content": "do dogs love dogs ?",
"category": "animals",
"type": "internal"

}

###

GET http://localhost:5000/answers/73