# register a new user
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Mostafa",
    "email": "mostafa.othman@digitalcareerinstitute.org",
    "password": "123456789"
}