@baseUrl = http://localhost:5000
### GET Users #########################
GET {{baseUrl}}/users

###  Create User ##########################
POST {{baseUrl}}/users
Content-Type: application/json

{
"username":"juja",
"password": "jay jay",
"email": "juja@gmail.com",
"mainAd" :{
     "city":"shiraz",
     "country":"iran",
     "zip":26466
}



}


###
 # Delete a User  ##############################

DELETE {{baseUrl}}/users/63f4902c510ae2e9d10c234f

####

# delete all the users

DELETE {{baseUrl}}/users/

###
# GET the questions##########################################

GET http://localhost:5000/questions

###
# create new question ########################################
POST http://localhost:5000/questions/
Content-Type: application/json

{
"author" : "63f49a51d40bb14d2a601c4a",
"title"  : "i am ,",
"content": "can i have ------?",
"category": "general",
"type": "external"

}


### 

# delete a question #########################################
DELETE  http://localhost:5000/questions/63f48c5a9dd1e8c716785b98

###

# delte all UESERS ###################

DELETE {{baseUrl}}/users



###
#  update a question ########################################
PUT http://localhost:5000/questions/63ece9d3385bcaee5060a487
Content-Type: application/json

{

"author" : "63f25d191dd4aeff25d88e1d",
"title"  : "tigers",
"content": "do dogs love dogs ?",
"category": "animals",
"type": "internal"

}
###

DELETE {{baseUrl}}/questions
